version: '3'

services:
  mongo-db:
    image: mongo
    ports:
      - 27010:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=*changeme*
      - MONGO_INITDB_ROOT_PASSWORD=*changeme*
    volumes:
      - db-data:/data/db
  
  mongo-express:
    image: mongo-express
    ports:
      - 8083:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=*same as MONGO_INITDB_ROOT_USERNAME*
      - ME_CONFIG_MONGODB_ADMINPASSWORD=*same as MONGO_INITDB_ROOT_PASSWORD*
      - ME_CONFIG_MONGODB_SERVER=mongo-db

volumes:
  db-data:
    driver: local 